export enum StatusCode {
  SUCCESS = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHENTICATED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
  BAD_GATEWAY = 502
};

export enum ErrorDescription {
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  MAINTENANCE = 'MAINTENANCE',
  FORBIDDEN = 'FORBIDDEN',
  QUERY_EXCEPTION = 'QUERY_EXCEPTION',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
  UNHANDLED_EXCEPTION = 'UNHANDLED_EXCEPTION',
  CLIENT_EXCEPTION = 'CLIENT_EXCEPTION',
  SERVER_EXCEPTION = 'SERVER_EXCEPTION',
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  API_KEY_INVALID = 'API_KEY_INVALID',
  NOT_FOUND = 'NOT_FOUND',
  BAD_GATEWAY = 'BAD_GATEWAY'
}

export enum UserRole {
  ADMIN = 'ADMIN',
  USER = 'USER'
}
